version: "3.2"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - splash
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-project.settings.development}
      - DATABASE_HOST=db
      - DATABASE_NAME=${DATABASE_NAME:-tipresias}
      - GRAPHIQL=True
    command: python3 manage.py runserver 0.0.0.0:8000
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - tipresias_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    stdin_open: true
    tty: true
    depends_on:
      - backend
    command: yarn start
  tipping:
    build: ./tipping
    command: npm start
    depends_on:
      - backend
      - faunadb
    env_file: .env
    environment:
      PYTHONPATH: "./src"
      PORT: 3333
      DATABASE_HOST: faunadb:8443
      DATA_SCIENCE_SERVICE: http://host.docker.internal:8008
      TIPRESIAS_APP: http://backend:8000
      AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
      ROLLBAR_TOKEN: rollbar_token
    ports:
      - "3333:3333"
    stdin_open: true
    tty: true
    volumes:
      - ./tipping:/app
      - /app/node_modules
      - ${HOME}/.aws:/app/.aws
  browser_test:
    build: ./browser_test
    depends_on:
      - frontend
    volumes:
      - ./browser_test:/app
      - /app/node_modules
      # Need to use 'host' network mode to avoid cross-host errors
      # from Webpack server
    network_mode: "host"
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - "5432:5432"
  faunadb:
    image: fauna/faunadb:latest
    ports:
      - "8443:8443" # Base API
      - "8084:8084" # GQL Api
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
volumes:
  tipresias_node_modules:
    external: true
