version: "3.2"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - tipresias_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    stdin_open: true
    tty: true
    command: yarn start
  browser_test:
    build: ./browser_test
    depends_on:
      - frontend
    volumes:
      - ./browser_test:/app
      - /app/node_modules
      # Need to use 'host' network mode to avoid cross-host errors
      # from Webpack server
    network_mode: "host"
volumes:
  tipresias_node_modules:
    external: true
