version: "3.2"
services:
  backend:
    image: cfranklin11/tipresias_backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: project.settings.test
      DATABASE_HOST: db
      EMAIL_RECIPIENT: test@test.com
      SENDGRID_API_KEY: test
      CI: 1
      DATABASE_NAME: $DATABASE_NAME
      DATA_SCIENCE_SERVICE: $DATA_SCIENCE_SERVICE
      DATA_SCIENCE_SERVICE_TOKEN: $DATA_SCIENCE_SERVICE_TOKEN
    command: python3 manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:11.6
    environment:
      POSTGRES_DB: $DATABASE_NAME
