name: automerge
on:
  check_suite:
    types:
      - completed
    branches-ignore:
      # Ignoring packages with a history of breaking deploys/production
      # without breaking tests
      - "dependabot/docker/**/*"
      - "dependabot/**/serverless*"
      - "dependabot/**/react-scripts*"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies"
          MERGE_METHOD: merge
          MERGE_FILTER_AUTHOR: "dependabot[bot]"
          MERGE_FORKS: false
          MERGE_RETRY_SLEEP: 600000
