name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up code coverage monitoring
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          builder: ${{ steps.buildx.outputs.name }}
          tags: cfranklin11/tipresias_frontend:latest
          load: true
      - name: Build browser_test Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./browser_test
          builder: ${{ steps.buildx.outputs.name }}
          tags: cfranklin11/tipresias_browser_test:latest
          load: true
      - name: Lint
        if: ${{ always() }}
        run: |
          docker run --rm cfranklin11/tipresias_frontend:latest yarn run eslint src
      - name: Check types
        if: ${{ always() }}
        run: |
          docker run --rm cfranklin11/tipresias_frontend:latest yarn run flow
      - name: Run unit tests
        if: ${{ always() }}
        run: |
          docker run --rm -e CI=true cfranklin11/tipresias_frontend:latest yarn run test:unit
      - name: Run integration/system tests
        if: ${{ always() }}
        env:
          DATA_SCIENCE_SERVICE: ${{ secrets.DATA_SCIENCE_SERVICE }}
          DATA_SCIENCE_SERVICE_TOKEN: ${{ secrets.DATA_SCIENCE_SERVICE_TOKEN }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        run: |
          docker-compose -f docker-compose.ci.yml up --no-start

          ./scripts/update_frontend_gql_types.sh docker-compose.ci.yml
          docker-compose -f docker-compose.ci.yml stop

          ./scripts/browser_tests.sh docker-compose.ci.yml
          docker-compose -f docker-compose.ci.yml stop
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: cypress-screenshots
          path: ./browser_test/cypress/screenshots/
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: cfranklin11
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push updated images
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cfranklin11/tipresias_frontend:latest
          docker push cfranklin11/tipresias_browser_test:latest
