name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      CI: 1
      DATA_SCIENCE_SERVICE: ${{ secrets.DATA_SCIENCE_SERVICE }}
      DATA_SCIENCE_SERVICE_TOKEN: ${{ secrets.DATA_SCIENCE_SERVICE_TOKEN }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      FRONTEND_IMAGE: cfranklin11/tipresias_frontend:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.FRONTEND_IMAGE }}
          load: true
      - name: Lint
        if: ${{ always() }}
        run: |
          docker run --rm $FRONTEND_IMAGE npm run lint
      - name: Check types
        if: ${{ always() }}
        run: |
          docker run --rm $FRONTEND_IMAGE npx tsc
      - name: Run unit tests
        if: ${{ always() }}
        run: |
          docker run --rm -e CI=true $FRONTEND_IMAGE npm run test
      - name: GQL integration tests
        id: gql_integration_tests
        if: ${{ always() }}
        run: |
          docker-compose -f docker-compose.ci.yml build
          docker-compose -f docker-compose.ci.yml up --no-start
          ./scripts/update_frontend_gql_types.sh
      - name: Save updated GQL schema
        uses: actions/upload-artifact@v2
        if: ${{ always() && steps.gql_integration_tests.outcome == 'failure' }}
        with:
          name: gql-schema
          path: ./schema.json
      - name: Set up Cypress tests
        if: ${{ always() }}
        run: ./scripts/setup_browser_tests.sh
      - name: Run Cypress tests
        id: cypress
        uses: cypress-io/github-action@v2
      - name: Save Cypress screenshots
        uses: actions/upload-artifact@v2
        if: ${{ always() && steps.cypress.outcome == 'failure' }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v1
        with:
          username: cfranklin11
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push updated images
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push $FRONTEND_IMAGE
      - name: Configure AWS credentials
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Upload source maps to Rollbar
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./scripts/upload_source_maps.sh
      - name: Upload static files to S3
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm run build
          aws s3 sync build s3://tipresias.net
